name: learn-githun-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-slim
    steps:
      - uses: checkout/action@v5
      - uses: action/setup-node@v4
        with:
          node-version: '20'
      - run: npm install -g bats
      - run: bats -v
